-- Seed: informational_resources
-- Source: Casey Family Programs Trello Board Export
-- Generated: 2026-02-25
-- Cards: 25
--
-- This file was generated by supabase/scripts/generate-seed.ts
-- To regenerate: npx tsx supabase/scripts/generate-seed.ts

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Red Cards/Tarjetas Rojas',
  'All people in the United States, regardless of immigration status, have certain rights and protections under the U.S. Constitution. The ILRC''s Red Cards help people assert their rights and defend themselves in many situations, such as when ICE agents go to a home.',
  'https://www.ilrc.org/red-cards-tarjetas-rojas',
  'flyer',
  'Legal Services',
  'national',
  '{"en","es"}',
  '{"foster_youth","caseworkers","families"}',
  'Immigrant Legal Resource Center (ILRC)',
  '{"ice","rights","red-card","enforcement","know-your-rights","bilingual"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'CA Benefits Guide for Non-Citizens (English & Espanol)',
  'From the Immigrant Legal Resource Center--Public Benefits for Noncitizens',
  'https://oag.ca.gov/immigrant/resources',
  'guide',
  'Legal Services',
  'CA',
  '{"en","es"}',
  '{"foster_youth","caseworkers"}',
  'Immigrant Legal Resource Center (ILRC)',
  '{"benefits","california","noncitizens","public-benefits","bilingual"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'PRUCOL--Immigration Status--Person Residing Under the Color of Law',
  'Policy guide on PRUCOL (Person Residing Under the Color of Law) immigration status and eligibility for the Cash Assistance Program for Immigrants (CAPI). Covers qualified alien definitions, legal immigrant categories, and 11 specific non-citizen categories eligible under PRUCOL including those with deferred action status, approved I-130 petitions, and victims of trafficking or domestic violence.',
  'http://epolicy.dpss.lacounty.gov/epolicy/server?prj=ePolicyMaster&area=general&type=responsivehelp&tpc=mergedProjects%2FCAPI%2FCAPI%2F49-010_Eligibility_for_CAPI%2F49-010_Eligibility_for_CAPI_.htm',
  'policy_brief',
  'Legal Services',
  'CA',
  '{"en"}',
  '{"caseworkers"}',
  'California Department of Social Services',
  '{"prucol","immigration-status","capi","eligibility","benefits","policy"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Grounding the Immigration Narrative in Children & Families',
  'From the Young Center for Immigrant Children’s Rights.

Narrative Change Working Group Reference Sheet',
  '/assets/files/resources/young-center-immigration-messaging.pdf',
  'guide',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'Young Center for Immigrant Children''s Rights',
  '{"narrative","messaging","children","families","immigration","advocacy"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'CALIFORNIA RAPID RESPONSE NETWORKS',
  'If the person was detained by ICE within the last 24 hours, contact your local rapid response hotline. Click below for more information.',
  'https://www.ccijustice.org/carrn',
  'referral_tool',
  'Legal Services',
  'CA',
  '{"en"}',
  '{"foster_youth","caseworkers","families"}',
  'California Collaborative for Immigrant Justice (CCIJ)',
  '{"ice","detention","rapid-response","hotline","california","emergency"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'NCYL FAQs: Caregiver Affidavit for Unaccompanied Immigrant Youth',
  'Frequently asked questions from the National Center for Youth Law (NCYL) about using the Caregiver Affidavit as a non-relative or relative sponsor of unaccompanied immigrant youth. Covers legal responsibilities and processes for caregivers.',
  NULL,
  'guide',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","families"}',
  'National Center for Youth Law (NCYL)',
  '{"caregiver","affidavit","unaccompanied-youth","sponsorship","legal","ncyl"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'KIND Know Your Rights Flyer (English)',
  NULL,
  '/assets/files/resources/kind-know-your-rights-english.pdf',
  'flyer',
  'Legal Services',
  'national',
  '{"en"}',
  '{"foster_youth"}',
  'Kids in Need of Defense (KIND)',
  '{"know-your-rights","youth","flyer","kind"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Native American Health Center: Know Your Rights Poster',
  'Know Your Rights poster designed for display in community health centers and service agencies. Visual resource covering rights during immigration enforcement encounters.',
  'https://www.canva.com/design/DAGcrWK5VUY/HGJbUAj0a-XOHPCJnO2KZA/view?utm_content=DAGcrWK5VUY&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=hb0df571bfc',
  'poster',
  'Legal Services',
  'national',
  '{"en"}',
  '{"foster_youth","caseworkers"}',
  'Native American Health Center',
  '{"know-your-rights","poster","enforcement","visual-aid"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'State Benefit Map',
  'Interactive web tool from the National Immigrant Women''s Advocacy Project (NIWAP) to help victim advocates, attorneys, judges, and other professionals screen and identify which immigrant survivors and children qualify for state or federally funded public benefits, programs, and services.',
  'https://niwaplibrary.wcl.american.edu/benefits-map/#info',
  'referral_tool',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'National Immigrant Women''s Advocacy Project (NIWAP)',
  '{"benefits","state-map","eligibility","screening","survivors","public-benefits"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Brief Training/Talk--"Supporting Unaccompanied Immigrant Youth"',
  '24-minute video training on supporting unaccompanied immigrant youth (children 18 and younger) entering the United States from the Mexican border. Covers challenges this population faces and strategies to support these youth and their families.',
  'https://casey.sabacloud.com/Saba/Web_spf/NA3P1PRD0064/common/leclassview/dowbt-SIFWEBBASED',
  'video',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers"}',
  'Casey Family Programs',
  '{"training","unaccompanied-youth","video","onboarding","border","support"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'The Laken Riley Act & Juvenile Delinquency',
  'Immigration Legal Resource Center--The Laken Riley Act & Juvenile Delinquency',
  '/assets/files/resources/laken-riley-act-juvenile-delinquency.pdf',
  'policy_brief',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'Immigrant Legal Resource Center (ILRC)',
  '{"laken-riley","juvenile","delinquency","legislation","immigration","policy"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Protected Areas Policies--Recission of Policy by new Adminstration',
  'Analysis of the rescission of protected areas (sensitive locations) policies by the current administration and its impact on safety for immigrant communities.',
  '/assets/files/resources/protected-areas-policies.pdf',
  'policy_brief',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'Immigrant Legal Resource Center (ILRC)',
  '{"protected-areas","sensitive-locations","enforcement","policy","safety"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'California Access to Justice Commission--Supplemental Legal Aid Funding for Vulnerable Populations',
  'California Access to Justice Commission (CALATJ) supplemental legal aid funding for vulnerable populations including immigrants and LGBTQ+ community. $4,875,000 available to nonprofits providing civil legal services. Grants range from $25,000-$150,000 per project. Priorities include protecting constitutional and legal rights of immigrants facing detention and strengthening cybersecurity for legal services programs.',
  'https://calatj.org/grants/funding-for-vulnerable-populations',
  'guide',
  'Legal Services',
  'CA',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'California Access to Justice Commission (CALATJ)',
  '{"legal-aid","funding","grants","california","nonprofits","immigrants"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'CA Attorney General: Immigrant Resources',
  'Official California Attorney General resource page for immigrant communities. Includes know-your-rights information, complaint filing, and links to legal services.',
  'https://oag.ca.gov/immigrant/resources',
  'referral_tool',
  'Legal Services',
  'CA',
  '{"en"}',
  '{"foster_youth","caseworkers","families"}',
  'California Attorney General',
  '{"california","attorney-general","immigrant-resources","rights","legal-services"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Referral tool for caseworkers',
  NULL,
  '/assets/files/resources/aba-immigration-referral-tool.pdf',
  'referral_tool',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers"}',
  'American Bar Association (ABA)',
  '{"referral","immigration","caseworker-tool","legal-aid","aba"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'The Center on Immigration and Child Welfare Initiative',
  'The Center on Immigration and Child Welfare (CICW) coordinates three professional networks: the Immigration and Child Welfare Practice Network, the Research Network, and the Legal Network. Facilitates collaboration among professionals across the U.S. working at the intersection of immigration and child welfare.',
  'https://cimmcw.org/',
  'referral_tool',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'Center on Immigration and Child Welfare (CICW)',
  '{"child-welfare","immigration","network","collaboration","cicw"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Make a plan',
  NULL,
  '/assets/files/resources/make-a-plan-english.pdf',
  'toolkit',
  'Family & Childcare',
  'national',
  '{"en"}',
  '{"families"}',
  'Women''s Refugee Commission',
  '{"family-plan","separation","preparedness","parents","migrant-families"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Guidance for Child Welfare Agencies to Prepare for a 2nd Trump Administration',
  'Trump 2.0 Top Tips Fact Sheet',
  '/assets/files/resources/trump-2-top-tips-fact-sheet.pdf',
  'fact_sheet',
  'Family & Childcare',
  'national',
  '{"en"}',
  '{"caseworkers"}',
  'Center on Immigration and Child Welfare (CICW)',
  '{"child-welfare","agency-guidance","immigration-enforcement","preparedness"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Fact Sheet for Child Welfare & Guardianship Stakeholders: ICE Policies and Standards Related to Detained Parents & Legal Guardians',
  'Fact sheet for child welfare and guardianship stakeholders on ICE policies and standards related to detained parents and legal guardians. Covers processes for maintaining family connections during immigration detention.',
  NULL,
  'fact_sheet',
  'Family & Childcare',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'Center on Immigration and Child Welfare (CICW)',
  '{"ice","detention","parents","guardianship","child-welfare","fact-sheet"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'ICE Online Detainee Locator System',
  'Information about the ICE Online Detainee Locator System — a tool for locating individuals in immigration detention. Used by caseworkers and families to find detained parents or guardians.',
  'https://locator.ice.gov/odls/#/index',
  'referral_tool',
  'Family & Childcare',
  'national',
  '{"en"}',
  '{"caseworkers","families"}',
  'Center on Immigration and Child Welfare (CICW)',
  '{"ice","detainee-locator","detention","family-search","tool"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Step-by-Step Family Preparedness Plan',
  NULL,
  'https://www.ilrc.org/resources/step-step-family-preparedness-plan',
  'toolkit',
  'Family & Childcare',
  'national',
  '{"en"}',
  '{"families","foster_youth"}',
  'Immigrant Legal Resource Center (ILRC)',
  '{"family-plan","preparedness","step-by-step","separation","emergency"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Parental Toolkit (Spanish)',
  NULL,
  '/assets/files/resources/parental-toolkit-spanish.pdf',
  'toolkit',
  'Family & Childcare',
  'national',
  '{"es"}',
  '{"families"}',
  'Women''s Refugee Commission',
  '{"parental-toolkit","spanish","family-plan","preparedness"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'What do child welfare leaders need to know about supporting families when caregivers are facing immigration-enforced detention or deportation?',
  NULL,
  '/assets/files/resources/casey-immigration-resources.pdf',
  'guide',
  'Family & Childcare',
  'national',
  '{"en"}',
  '{"caseworkers"}',
  'Casey Family Programs',
  '{"child-welfare","detention","deportation","leadership","casey"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'Protecting Sensitive Locations Act',
  'Overview of the Protecting Sensitive Locations Act from the Center for Law and Social Policy (CLASP). Covers protections for schools, hospitals, churches, and other sensitive locations from immigration enforcement actions.',
  'https://www.clasp.org/protecting-sensitive-locations-act/',
  'policy_brief',
  'Legal Services',
  'national',
  '{"en"}',
  '{"caseworkers","advocates"}',
  'Center for Law and Social Policy (CLASP)',
  '{"sensitive-locations","legislation","schools","hospitals","enforcement","clasp"}'
);

INSERT INTO informational_resources (title, description, url, resource_type, category, geography, languages, audience, source_org, tags)
VALUES (
  'KIND Know Your Rights Flyer (Spanish)',
  NULL,
  '/assets/files/resources/kind-know-your-rights-spanish.pdf',
  'flyer',
  'Legal Services',
  'national',
  '{"es"}',
  '{"foster_youth"}',
  'Kids in Need of Defense (KIND)',
  '{"know-your-rights","youth","flyer","spanish","kind"}'
);
